---
- name: Install git from package repository
  apt: name=git-core
  become: true

- name: Copy global git configuration
  copy: src=gitconfig dest=~/.gitconfig

- name: Copy global git ignore
  copy: src=gitignore dest=~/.gitignore
